### ISSUE TITLE
Update tugas SistemInformasiIF

### ISSUE THREAD

**Issue by Rozii23** [Rozii23/SistemInformasiIF#3]
# Sinkronisasi Branch ke Repository Utama untuk Halaman Pengumuman dan Data Dosen

### **Masalah yang Ditemukan:**
1. **Sunil Hukmi** telah memperbarui halaman **Pengumuman**, tetapi perubahan tersebut **belum di-push** ke repository utama. Akibatnya, halaman tersebut **belum bisa ditampilkan** pada sistem utama.  
2. **Taufik Muhaimin** telah membuat data **dosen**, namun perubahan tersebut juga **belum di-push** ke repository utama dan hanya ada di branch masing-masing. Oleh karena itu, data dosen tersebut **belum bisa dijalankan** di sistem utama.  

### **Fitur yang Diharapkan:**
- **Merge Branch ke Main**  
  Melakukan **pull request (PR)** dari branch masing-masing anggota (Sunil Hukmi dan Taufik Muhaimin) ke **branch main** di repository utama.  
- **Review dan Penggabungan Kode**  
  Melakukan review pada perubahan yang telah dibuat oleh kedua anggota dan menggabungkannya ke **branch main**.  
- **Sinkronisasi Sistem**  
  Memastikan semua fitur yang telah diperbarui bisa **berjalan di branch main** setelah digabungkan.

---

## To-Do List
- [ ] Sunil Hukmi melakukan **push** perubahan halaman **Pengumuman** ke repository utama.  
- [ ] Taufik Muhaimin melakukan **push** perubahan data **dosen** ke repository utama.  
- [ ] Membuat **pull request** untuk setiap branch yang telah diperbarui.  
- [ ] Review dan **merge** branch ke **main** oleh pemilik repository.  

---

## Label
- **Bug**  
- **Branch Sync**  
- **Enhancement**  

---

## Assignee
- @Sunilhukmi 
- @taufik523825 
- @*Rozii23*  

---

## Milestone
- **Sprint 1:** Sinkronisasi halaman **Pengumuman** dan data **dosen**.  

---

## Catatan Tambahan
Pemilik repository akan **mengelola dan memperbaiki merge** setelah semua perubahan telah di-push dan pull request dibuat oleh masing-masing anggota. Harap segera menyelesaikan **push branch** agar proses integrasi tidak tertunda.
